### ISSUE TITLE
Violation of Extra Origins' license

### ISSUE THREAD

**Issue by ChrysanthCow** [CoutteauSam/Seleni#10] opened 2023-06-13 14:45 UTC
[ModifySizePower.java](https://github.com/CoutteauSam/Seleni/blob/main/src/main/java/scouttea/seleni/common/powers/ModifySizePower.java)

## The rundown
Hi, so in Moriya's discord, somebody pointed out that you had used the Extra Origins Modify Size code for your Modify Size power.

## Why is this an issue?
Well, Extra Origins' license is All Rights Reserved, meaning that the author has to give permission for you to use the code (which MoriyaShiine has not and probably won't either).

## The solution
I'd recommend removing the class from the mod, or moriya may have to act as you did not have permission to use it.

**Comment by ChrysanthCow** [comment] 2023-06-14 13:34
I'm writing up resource documenting all of the size change methods thanks to this situation.

**Comment by QuantumXenon** [comment] 2023-06-17 09:30
Thanks for bringing this to my attention! As I have been maintaining this mod, I was not aware that this code portion was not suitably licensed. I'll change this as soon as possible to correct this issue.

**Comment by QuantumXenon** [comment] 2023-06-17 10:01
Sorry for any problems caused by this! I've now removed the problematic class. 

I will update the other versions of Seleni and make a release on CurseForge as soon as I can.

I've joined the Discord to contact Moriya on how to proceed from here.

**Comment by QuantumXenon** [comment] 2023-06-17 15:46
Closing this issue as all Extra Origins code has been removed and old versions of Seleni have been archived on CurseForge

**Closed as completed by QuantumXenon** 2023-06-17 15:46 UTC
